name: build-conda-action-build
# looks through these channels (locations) to find the following dependencies
channels:
  - defaults
  - conda-forge
# the required packages for the current project
dependencies:
  - conda=4.9.2
  - conda-build=3.20.5
  - conda-verify=3.4.2
